---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-schemas
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: k8s-schemas-rclone
    template:
      engineVersion: v2
      data:
        rclone.conf: |
          [b2]
          type = b2
          account = {{ .APPLICATION_KEY_ID }}
          key = {{ .APPLICATION_KEY }}
  dataFrom:
    - extract:
        key: backblaze
