---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kube-state-metrics
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.36.0@sha256:a9d0e8875e59c85868fe2ca9a73cd040af4efd0feac23ace5b7197a4db36b65f
  url: oci://ghcr.io/prometheus-community/charts/kube-state-metrics
