---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: prometheus-secrets
    template:
      engineVersion: v2
      data:
        # App
        GRAFANA_ADMIN_USER: "{{ .GRAFANA_ADMIN_USER }}"
        GRAFANA_ADMIN_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: grafana
