---
apiVersion: monitoring.giantswarm.io/v1alpha1
kind: Silence
metadata:
  name: singularity-memory-usage
spec:
  matchers:
    - name: alertname
      value: NodeMemoryHighUtilization
      isRegex: false
    - name: instance
      value: singularity.internal:9100
      isRegex: false
