---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: descheduler
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.33.0@sha256:5b8afe97256796788032adce5f13eb1d5159a20bf700d57c95011549c2f968c5
  url: oci://ghcr.io/home-operations/charts-mirror/descheduler
  verify:
    provider: cosign
