---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app crunchy-postgres-operator
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: pgo
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    monitoring: true
    install:
      clusterLabels:
        app.kubernetes.io/name: *app
