---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-cobblemon
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: minecraft
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      pullPoicy: Always
    minecraftServer:
      eula: "TRUE"
      version: "1.20.1"
