---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gatus
  namespace: &namespace monitoring
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  components: [../../../../components/postgres]
  dependsOn:
    - name: cloudnative-pg
      namespace: database
  path: ./kubernetes/apps/monitoring/gatus/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
  postBuild:
    substitute:
      APP: *app
      NS: *namespace
      GATUS_SUBDOMAIN: status
  patches:
    - target:
        kind: HelmRelease
        name: gatus
      patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: gatus
        spec:
          values:
            ingress:
              app:
                annotations:
                  gethomepage.dev/enabled: "true"
                  gethomepage.dev/icon: gatus.png
                  gethomepage.dev/name: Gatus
                  gethomepage.dev/group: monitoring
                  gethomepage.dev/description: Status Page
