---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wkd-server
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      wkd-server:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        # containers:
        #   app:
        #     image:
        #       repository:
        #       tag:
    # service:
    #   app:
    #     controller: *app
    #     ports:
    #       http:
    #         port:
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.kinzoku.dev
        hosts:
          - host: wkd.kinzoku.dev
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
