---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: grafana
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 9.2.0@sha256:bae68c1278e1492b83110fdb8b46cb479abcb275bbfd85a563db342cbc16df18
  url: oci://ghcr.io/grafana/helm-charts/grafana
