---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: thanos-secret
    template:
      engineVersion: v2
      data:
        # App
        # AWS_ACCESS_KEY_ID: "{{ .MINIO_ACCESS_KEY }}"
        # AWS_SECRET_ACCESS_KEY: "{{ .MINIO_SECRET_KEY }}"
        AWS_ACCESS_KEY_ID: "{{ .MINIO_ROOT_USER }}"
        AWS_SECRET_ACCESS_KEY: "{{ .MINIO_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: minio
