---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vikunja
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vikunja-secret
    template:
      engineVersion: v2
      data:
        VIKUNJA_SERVICE_JWTSECRET: "{{ .VK_JWT_SECRET }}"
        config.yml: |
          auth:
            local:
              enabled: false
            openid:
              enabled: true
              providers:
                - name: "kinzokudev auth"
                  authurl: {{ .OIDC_URL }}
                  clientid: {{ .OIDC_ID }}
                  clientsecret: {{ .OIDC_SECRET }}
  dataFrom:
    - extract:
        key: vikunja
