---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vikunja
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      vikunja:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/vikunja/vikunja
              tag: 0.24.6@sha256:ed1f3ed467fecec0b57e9de7bc6607f8bbcbb23ffced6a81f5dfefc794cdbe3b
            command: ["/app/vikunja/vikunja"]
            env:
              VIKUNJA_SERVICE_TIMEZONE: "America/New_York"
              VIKUNJA_SERVICE_JWTSECRET:
                valueFrom:
                  secretKeyRef:
                    name: vikunja-secret
                    key: VIKUNJA_SERVICE_JWTSECRET
              VIKUNJA_SERVICE_JWTTTL: "86400" # 1 day
              VIKUNJA_SERVICE_JWTTTLLONG: "1209600" # 2 weeks
              VIKUNJA_SERVICE_INTERFACE: ":8080"
              VIKUNJA_SERVICE_PUBLICURL: "https://vk.kinzoku.dev"
              VIKUNJA_SERVICE_MAXITEMSPERPAGE: "200"
              VIKUNJA_SERVICE_ENABLEREGISTRATION: "${CONFIG_VIKUNJA_REGISTRATION:=false}"
              VIKUNJA_SERVICE_CUSTOMLOGOURL: "https://raw.githubusercontent.com/kinzokudev/home-ops/main/assets/repo_logo.png"
              VIKUNJA_SENTRY_ENABLED: "false"
              VIKUNJA_DATABASE_TYPE: "postgres"
              VIKUNJA_DATABASE_HOST:
                valueFrom:
                  secretKeyRef:
                    name: &pgsec "vikunja-pg-app"
                    key: host
              VIKUNJA_DATABASE_DATABASE:
                valueFrom:
                  secretKeyRef:
                    name: *pgsec
                    key: dbname
              VIKUNJA_DATABASE_USER:
                valueFrom:
                  secretKeyRef:
                    name: *pgsec
                    key: username
              VIKUNJA_DATABASE_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: *pgsec
                    key: password
              VIKUNJA_DATABASE_SSLMODE: "require"
              VIKUNJA_DATABASE_SSLROOTCERT: "/tls/pg-ca.crt"
              VIKUNJA_METRICS_ENABLED: "true"
              VIKUNJA_LOG_PATH: "/dev/stdout"
              VIKUNJA_DEFAULTSETTINGS_AVATAR_PROVIDER: "initials"
            securityContext: &sc
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
            envFrom:
              - secretRef:
                  name: vikunja-secret
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.kinzoku.dev
        hosts:
          - host: vk.kinzoku.dev
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        type: secret
        name: vikunja-secret
        advancedMounts:
          vikunja:
            app:
              - subPath: "config.yml"
                path: "/etc/vikunja/config.yml"
                readOnly: true
      pg:
        type: secret
        name: vikunja-pg-ca
        defaultMode: 0400
        advancedMounts:
          vikunja:
            app:
              - subPath: "ca.crt"
                path: "/tls/pg-ca.crt"
                readOnly: true
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: &uid 1000
        runAsGroup: *uid
        fsGroup: *uid
        fsGroupChangePolicy: "Always"
        seccompProfile: { type: "RuntimeDefault" }
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
    serviceMonitor:
      app:
        serviceName: vikunja
        endpoints:
          - port: http
            scheme: http
            path: "/api/v1/metrics"
            interval: 1m
            scrapeTimeout: 30s
