---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: prometheus-operator-crds
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 20.0.0@sha256:312e1a90cd159d29af272602789d39a40662d2ba6c0178a7425e0194ee1377ed
  url: oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds
