---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: karakeep
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: karakeep-secret
    template:
      engineVersion: v2
      data:
        encryption_key: "{{ .KARAKEEP_ENCRYPTION_KEY }}"
        meilisearch_master_key: "{{ .KARAKEEP_MEILISEARCH_MASTER_KEY }}"
  dataFrom:
    - extract:
        key: karakeep
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: karakeep-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: karakeep-auth-secret
    template:
      engineVersion: v2
      data:
        OAUTH_CLIENT_ID: "{{ .KARAKEEP_OAUTH_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .KARAKEEP_OAUTH_CLIENT_SECRET }}"
        OAUTH_WELLKNOWN_URL: "{{ .KARAKEEP_OAUTH_WELLKNOWN_URL }}"
        OAUTH_PROVIDER_NAME: "authentik"
        OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: "true"
  dataFrom:
    - extract:
        key: karakeep
