# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:qws72grS9MET5vG4U2hdb+tDVXo4xUJiQs6Ga5RpkuY=,iv:C/mJXpMn7MOUg6XHTLh5I6pDJmU12PaEQI7EW2gyjbQ=,tag:e6oi2R5wWAE3bDNbi6WSaQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14q34qn75m29r5qrsakrs4mnulusjcy0w3tlzejygkvm46n5vpddqkjykpe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL3JFUW5pN1dMUWlBQlVT
        RmZGZzB4UG5VMHBqYllOWUhlN092MWpDc3dnCk4zVmdEQ1h5OTRSd284a3ZScElM
        VGRUTENYTEd6WjdLWUlvZ2x4ZEltRHcKLS0tIEZsTHY1dUQ1cDhaV016QVFjTEhO
        VE9TYWE4UENSR1lIWWNQWXBYR2cxLzQK+kNKapVuGTT49hrodS/yFSpEZTzJG+jg
        PK2CFVT//KaChT27viNRxP2JrCPqQSWqWi9SaegNsN40SaTMcm2D3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-12T13:37:07Z"
  mac: ENC[AES256_GCM,data:EnyNlpbdX4FPacEU5GtTMudy9NrCMmr4/aoiIuBCaysICAkVMa1JHX//G0f1i3YT1c9oz5gx94TSdPLsODi9CEWjzS+X8lBlKobEkgStuv2E4YOK0YhpPzyfL6xVSMKcgu3nhu20iZl3azV/dXb0ipYbIoaPAHOE3Sko+WAFjEQ=,iv:A84qK8qTT+wfZaWdCateJHfBlfDf3JdtKgc1n/nBO/4=,tag:rat4IWwBfxYfRB3iYunTpA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
