---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-secret
    creationPolicy: Owner
  data:
    - secretKey: pushover_api_token
      remoteRef:
        key: alertmanager
        property: ALERTMANAGER_PUSHOVER_KEY
    - secretKey: pushover_api_userkey
      remoteRef:
        key: pushover
        property: PUSHOVER_USER_KEY
