---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-pg
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:17.4-v0.4.0
  enableSuperuserAccess: true
  primaryUpdateMethod: switchover
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  storage:
    storageClass: openebs-hostpath
    size: 5Gi
  monitoring:
    enablePodMonitor: true
  managed:
    roles:
      - name: grafana
        superuser: true
        login: true
  backup:
    retentionPolicy: "14d"
    barmanObjectStore:
      destinationPath: s3://cnpg-backups
      endpointURL: https://s3.kinzoku.dev
      wal:
        compression: bzip2
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-secret
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-secret
          key: AWS_SECRET_ACCESS_KEY
  bootstrap:
    initdb:
      database: grafana
      owner: grafana
      secret:
        name: grafana-postgres-user
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: grafana-pg-backup
spec:
  schedule: "@daily"
  cluster:
    name: grafana-pg
