---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: convertx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: convertx-secret
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .CONVERTX_JWT_SECRET }}"
  dataFrom:
    - extract:
        key: convertx
