---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app karma
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      main:
        type: deployment
        replicas: 3
        containers:
          main:
            image:
              repository: ghcr.io/prymitive/karma
              tag: v0.121@sha256:9f0ad820df1b1d0af562de3b3c545a52ddfce8d7492f434a2276e45f3a1f7e28
            env:
              TZ: America/New_York
              ALERTMANAGER_URI: http://alertmanager-local.monitoring.svc:9093
              ALERTMANAGER_EXTERNAL_URI: https://am.kinzoku.dev
              ALERTMANAGER_PROXY: 'true'
              FILTERS_DEFAULT: '@state!=suppressed,alertname!=Watchdog'
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: [ALL]
            resources:
              requests:
                cpu: 10m
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
    ingress:
      main:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.kinzoku.dev
        hosts:
          - host: karma.kinzoku.dev
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: Always
        seccompProfile: {type: RuntimeDefault}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
