---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      data:
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_EMAIL__FROM: "{{ .AUTHENTIK_EMAIL__FROM }}"
        AUTHENTIK_EMAIL__HOST: "{{ .AUTHENTIK_EMAIL__HOST }}"
        AUTHENTIK_EMAIL__PORT: "{{ .AUTHENTIK_EMAIL__PORT }}"
        AUTHENTIK_EMAIL__USE_TLS: "{{ .AUTHENTIK_EMAIL__USE_TLS }}"
        AUTHENTIK_EMAIL__USE_SSL: "{{ .AUTHENTIK_EMAIL__USE_SSL }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .AUTHENTIK_EMAIL__USERNAME }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .AUTHENTIK_EMAIL__PASSWORD }}"
        AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT: "{{ .AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT }}"
        AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME: "{{ .AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME }}"
        AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN: "{{ .AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN }}"
        AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY: "{{ .MINIO_ACCESS_KEY }}"
        AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY: "{{ .MINIO_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: minio
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-tokens
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-tokens-secret
    creationPolicy: Owner
    template:
      data:
        AUTHENTIK_TOKEN_LDAP: "{{ .AUTHENTIK_TOKEN_LDAP }}"
        # AUTHENTIK_TOKEN_RADIUS: "{{ .AUTHENTIK_TOKEN_RADIUS }}"
  dataFrom:
    - extract:
        key: authentik
