---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-outpost
spec:
  ingressClassName: internal
  rules:
    - host: &host authentik.kinzoku.dev
      http:
        paths:
          - pathType: Prefix
            path: "/outpost.goauthentik.io"
            backend:
              service:
                name: authentik
                port:
                  name: http
  tls:
    - hosts:
        - *host
