---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nullpointer
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      nullpointer:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: lastradev/0x0
              tag: latest@sha256:f6076b1bf13cea638ad5b299c347db74b28f4b0e0b969c8dd81ad0eca1b9029d
            env:
              DATABASE_URI:
                secretKeyRef:
                  name: nullpointer-pg-app
                  key: uri
              FLASK_APP: "fhost"
              APP_PORT: 8080
              MAX_SIZE: 512
          nginx:
            image:
              repository: lastradev/0x0-nginx
              tag: latest@sha256:1ce8fadb0bc72ec2f464751fff18b2592387e1bff2956342a608c73aaba6ac96
            env:
              MAX_SIZE: "512M"
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.kinzoku.dev
        hosts:
          - host: nullpointer.kinzoku.dev
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 30Gi
        advancedMounts:
          nullpointer:
            app:
              - path: /app/up
            nginx:
              - path: /etc/nginx/html/up
