---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nullpointer
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      nullpointer:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/kinzokudev/0x0-app
              tag: sha-d2ef5d1@sha256:c9ee68454b54a9992b627f9e4844b97d229a98906034338993fa76a9da1e5194
            env:
              DATABASE_URI:
                secretKeyRef:
                  name: nullpointer-pg-app
                  key: uri
              FLASK_APP: "fhost"
              APP_PORT: 8080
              MAX_SIZE: 1024
          nginx:
            image:
              repository: ghcr.io/kinzokudev/0x0-nginx
              tag: sha-d2ef5d1@sha256:38f99ad24fddc4d155069461592ed3245f22ab43603470d98bdf3d56fc28719c
            env:
              MAX_SIZE: "1024M"
              APP_IP: "127.0.0.1"
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.kinzoku.dev
          nginx.ingress.kubernetes.io/auth-url: |-
            http://authentik-proxy.security.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
            https://0x0.kinzoku.dev/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: &host 0x0.kinzoku.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 30Gi
        advancedMounts:
          nullpointer:
            app:
              - path: /app/up
            nginx:
              - path: /etc/nginx/html/up
