---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        # App
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_TAG }}"
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .KUBERNETES_CLOUDFLARE_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CLOUDFLARE_API_KEY }}"
        HOMEPAGE_VAR_LATITUDE: "{{ .HOMEPAGE_VAR_LATITUDE }}"
        HOMEPAGE_VAR_LONGITUDE: "{{ .HOMEPAGE_VAR_LONGITUDE }}"
        # Observability
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_ADMIN_USERNAME }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: cloudflare
    - extract:
        key: homepage
    - extract:
        key: grafana
