---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app it-tools
  namespace: &namespace selfhosted
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/selfhosted/it-tools/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  patches:
    - target:
        kind: HelmRelease
        name: it-tools
      patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: it-tools
        spec:
          values:
            ingress:
              app:
                annotations:
                  gethomepage.dev/enabled: "true"
                  gethomepage.dev/icon: it-tools.png
                  gethomepage.dev/name: "IT Tools"
                  gethomepage.dev/group: selfhosted
                  gethomepage.dev/description: Useful tools for developers
