---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: gha-runner-scale-set-controller
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.12.0@sha256:09b114ce9d3e313372bf046d685ec530a781211f3abceb096b6c63748e8a1806
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
