---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name "${APP}-crunchy-postgres"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        CLOUDFLARE_ACCOUNT_ID: "{{ .CLOUDFLARE_ACCOUNT_TAG }}"
        s3.conf: |
          [global]
          repo1-s3-key={{ .MINIO_ACCESS_KEY }}
          repo1-s3-key-secret={{ .MINIO_SECRET_KEY }}
        encryption.conf: |
          [global]
          repo1-cipher-pass={{ .CRUNCHY_PGO_CIPHER_PASS }}
  dataFrom:
    - extract:
        key: cloudflare
    - extract:
        key: minio
    - extract:
        key: crunchy-pgo
