---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}-postgres-pgdata"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 5Gi
