---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: smartctl-exporter
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.15.3@sha256:b152565b4df75d91c771397154c1893a2e2786e43774ee9967d32e2c04052997
  url: oci://ghcr.io/prometheus-community/charts/prometheus-smartctl-exporter
