---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: tf-files
  namespace: flux-system
spec:
  interval: 1m
  url: oci://ghcr.io/kinzokudev/manifests/terraform
  ref:
    tag: main
