---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 30m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: loki
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: openebs
      namespace: openebs-system
  valuesFrom:
    - targetPath: loki.storage.s3.accessKeyId
      kind: Secret
      name: &secret loki-secret
      valuesKey: AWS_ACCESS_KEY_ID
    - targetPath: loki.storage.s3.secretAccessKey
      kind: Secret
      name: *secret
      valuesKey: AWS_SECRET_ACCESS_KEY
  values:
    deploymentMode: SingleBinary
    loki:
      analytics:
        reporting_enabled: false
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      podAnnotations:
        configmap.reloader.stakater.com/reload: *secret
        secret.reloader.stakater.com/reload: *secret
      compactor:
        working_directory: /var/loki/compactor/retention
        delete_request_store: filesystem
        retention_enabled: true
      ingester:
        chunk_encoding: snappy
      storage:
        bucketNames:
          chunks: "loki"
        type: s3
        s3:
          insecure: false
          endpoint: "s3.kinzoku.dev"
          region: "us-east-1"
      schemaConfig:
        configs:
          - from: "2024-04-01" # quote
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      server:
        log_level: info
    backend:
      replicas: 0
    gateway:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    sidecar:
      image:
        repository: ghcr.io/kiwigrid/k8s-sidecar
      rules:
        searchNamespace: ALL
    lokiCanary:
      enabled: false
    test:
      enabled: false
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: openebs-hostpath
        size: 15Gi
