# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:i6HYyUPue/g6wRQOuUrJq7lttWLWNx1r1HdfTPGy5EF34TBWiQyndw==,iv:EdW5/yrpm90iQU/yWzwRpZtspegMrmjSVh82htoo8mk=,tag:wMF9lxLigXHIMuU0oyoUHA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14q34qn75m29r5qrsakrs4mnulusjcy0w3tlzejygkvm46n5vpddqkjykpe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMVE2WjlZeUl1QklkbEJK
        Y2c2OXZ6OU1zaUxvNUVBSTFDTG1qUytBQ0dZCnlnWE10d1pWREUvTm5SWUFXZi9P
        Q3pPY1ZTdmZEOHkvbXlDNktqUjVXclUKLS0tIFNNYjRPU0ZXeWNKelovMHJKTGp1
        M3dqRXBydis2RnlVRituUjNtWU54eUkK39EV3PrhICoFj3NvaIsmwJOhg8I6ZDvE
        1L+TgND6152T5tnognjL5VFykQb+wbz+JnpvWDZuihmod6+Djl1VAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-11T21:50:44Z"
  mac: ENC[AES256_GCM,data:9jsZVOO1+v3pRJWZ0qfJ346U8yLPEmlOsYFrmIjAQFCWKtXV9DxoBJ+OD6b39hdWeSCpzUHd97jVB//qq0sE5apJo1epwdw9/RJTAXuAMdM07gqiWB+FqyRtlrHoZ+Af1egavrLI5f8Y6djyuA7c++2WA+UkglFg4rOl18fI26o=,iv:vT6AAYWK3WliUtb/DXieQbAmNuB7yRMpOaQO7wQLfyw=,tag:j6QuppnCFyYo8TsLa0RwNA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
