---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kromgo
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      kromgo:
        type: deployment
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          main:
            image:
              repository: ghcr.io/kashalls/kromgo
              tag: v0.7.0@sha256:98202ba862023c1f78c6bc227f1de89d7777e5f621333511241a6242a230880e
            env:
              TZ: America/New_York
              PROMETHEUS_URL: http://vmsingle-victoria.monitoring.svc.cluster.local:8429
              SERVER_HOST: &host '[::]'
              SERVER_PORT: &http 8080
              HEALTH_HOST: *host
              HEALTH_PORT: &health 8888
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: [ALL]
            resources:
              requests:
                cpu: 10m
            probes:
              liveness:
                enabled: true
                custom: true
                spec: &probes
                  httpGet:
                    path: /-/health
                    port: *health
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  <<: *probes
                  httpGet:
                    path: /-/ready
                    port: *health
    service:
      kromgo:
        controller: kromgo
        ports:
          http:
            port: *http
            protocol: HTTP
            appProtocol: http
          health:
            port: *health
            protocol: HTTP
            appProtocol: http
    ingress:
      main:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.kinzoku.dev
        hosts:
          - host: kromgo.kinzoku.dev
            paths:
              - path: /
                service:
                  identifier: kromgo
                  port: http
    persistence:
      config:
        type: configMap
        name: kromgo-config
        globalMounts:
          - path: /kromgo/config.yaml
            subPath: config.yaml
            readOnly: true
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: &uid 568
        runAsGroup: *uid
        fsGroup: *uid
        fsGroupChangePolicy: Always
        seccompProfile: {type: RuntimeDefault}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
