---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discodrome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: discodrome-secret
    template:
      engineVersion: v2
      data:
        DISCORD_BOT_TOKEN: "{{ .DISCORD_BOT_TOKEN }}"
        DISCORD_TEST_GUILD: "{{ .DISCORD_SCC_SERVER_ID }}"
        DISCORD_OWNER_ID: "{{ .DISCORD_KIN_USER_ID }}"
        SUBSONIC_SERVER: "{{ .SUBSONIC_SERVER }}"
        SUBSONIC_USER: "{{ .SUBSONIC_USER }}"
        SUBSONIC_PASSWORD: "{{ .SUBSONIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: discodrome
