---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 74.0.0@sha256:4d8df20368064175ce23c97a07819570f90b83525dc80c849c697ac49fa655e4
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
