---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app nullpointer
  namespace: &namespace selfhosted
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/selfhosted/0x0/app
  components:
    - ../../../../components/gatus/external
    - ../../../../components/postgres
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      APP: *app
      NS: *namespace
      GATUS_SUBDOMAIN: "0x0"
  targetNamespace: *namespace
  timeout: 5m
  patches:
    - target:
        kind: HelmRelease
        name: nullpointer
      patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: nullpointer
        spec:
          values:
            ingress:
              app:
                annotations:
                  gethomepage.dev/enabled: "true"
                  gethomepage.dev/icon: mdi-null
                  gethomepage.dev/name: "0x0"
                  gethomepage.dev/group: selfhosted
                  gethomepage.dev/description: No-bullshit file hosting service
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-nullpointer
  namespace: &ns security
  labels: &l
    app.kubernetes.io/name: "nullpointer"
spec:
  interval: 1h
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kubernetes/apps/security/authentik/forward-auth
  dependsOn:
    - name: authentik
      namespace: security
  postBuild:
    substitute:
      AUTHENTIK_PROXY_HOST: "0x0.kinzoku.dev"
