---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app nullpointer
  namespace: &namespace selfhosted
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/selfhosted/0x0/app
  components:
    - ../../../../components/gatus/external
    - ../../../../components/postgres
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      APP: *app
      # GATUS_SUBDOMAIN: "0x0"
  targetNamespace: *namespace
  timeout: 5m
