---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-operator
spec:
  interval: 30m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: victoria-metrics-operator
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    createCRD: true
    operator:
      enable_converter_ownership: true
      useCustomConfigReloader: true
      psp_auto_creation_enabled: false
    env:
      - name: VM_VMALERTDEFAULT_CONFIGRELOADERCPU
        value: 10m
      - name: VM_VMAGENTDEFAULT_CONFIGRELOADERCPU
        value: 10m
    rbac:
      pspEnabled: false
    resources:
      requests:
        cpu: 20m
