---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: victoria-metrics-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.49.2@sha256:30badc42fe86e3aa934803b9123eed9ececc7c2abc0d334275eca9b5a6b4b80f
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-operator
