---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tf-cloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tf-cloud-secret
    template:
      engineVersion: v2
      data:
        terraform.tfrc: |-
          credentials "app.terraform.io" {
            token = "{{ .TF_CLOUD_TOKEN }}"
          }
  dataFrom:
    - extract:
        key: terraform

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tf-backend
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tf-backend-secret
    template:
      engineVersion: v2
      data:
        access_key: "{{ .MINIO_ACCESS_KEY }}"
        secret_key: "{{ .MINIO_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: minio
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: terraform
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tf-secret
    template:
      engineVersion: v2
      data:
        OP_CONNECT_TOKEN: "{{ .OP_CONNECT_TOKEN }}"
        OP_CONNECT_HOST: "http://singularity.internal:7070"
  dataFrom:
    - extract:
        key: 1password
