---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tf-cloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tf-cloud
    template:
      engineVersion: v2
      data:
        terraform.tfrc: |-
          credentials "app.terraform.io" {
            token = "{{ .TF_CLOUD_TOKEN }}"
          }
  dataFrom:
    - extract:
        key: terraform
