---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tofu-controller
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tofu-controller
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    runner:
      image:
        repository: ghcr.io/home-operations/opentofu-runner
        tag: 1.10.2@sha256:fb3d44e5aea7f30d93fc5c5cdde2356d19c888a37bfd1039c5b66f0fadd10aa0
    resources:
      limits:
        cpu: ~
        memory: ~
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
