---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tofu-controller
spec:
  interval: 1h
  chart:
    spec:
      chart: tofu-controller
      version: '0.16.0-rc.5'
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: tofu-controller
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: cloudflared
      namespace: network
  values:
    fullnameOverride: *app
    replicaCount: 1
    image:
      repository: ghcr.io/flux-iac/tofu-controller
      pullPolicy: IfNotPresent
      tag: v0.16.0-rc.5
    runner:
      image:
        repository: ghcr.io/flux-iac/tf-runner
        tag: v0.16.0-rc.5
        pullPolicy: IfNotPresent
      grpc:
        maxMessageSize: 30
    logLevel: info
    allowBreakTheGlass: false
    clusterDomain: cluster.local
    concurrency: 24
    caCertValidityDuration: 24h
    certRotationCheckFrequency: 30m
    resources:
      limits:
        cpu: ~
        memory: ~
      requests:
        cpu: 400m
        memory: 64Mi
