---
# yaml-language-server: $schema=https://crds.jank.ing/operator.victoriametrics.com/vmagent_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: victoria
spec:
  useStrictSecurity: true
  # metrics config
  selectAllByDefault: true
  remoteWrite:
    - url: http://vmsingle-victoria.monitoring.svc:8429/api/v1/write
    - url: http://vmsingle-alerts.monitoring.svc:8429/api/v1/write
  scrapeInterval: 60s
  vmAgentExternalLabelName: prometheus
  externalLabels:
    cluster: andromeda
  extraArgs:
    promscrape.maxScrapeSize: '200000000'  # kubelet cadvisor fails to scrape without increasing this
  # inlineRelabelConfig:
  #  - action: labeldrop
  #    source_labels: [prometheus, service, endpoint]
  # pod config
  replicaCount: 3
  statefulMode: true
  statefulStorage:
    volumeClaimTemplate:
      spec:
        storageClassName: openebs-hostpath
        resources:
          requests:
            storage: 10Gi
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: vmagent
          app.kubernetes.io/instance: victoria
  resources:
    requests:
      cpu: 150m
      memory: 256Mi
