---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app shlink-webui
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      shlink:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/shlinkio/shlink-web-client
              tag: 4.4.0@sha256:99988516ee0caf2059a485edaacab9759db0a3140c5a5c2634e0a97ac4d194bf
            env:
              TIMEZONE: "America/New_York"
              SHLINK_SERVER_URL: "https://l.kinzoku.dev"
              SHLINK_SERVER_NAME: "Shlink"
              SHLINK_SERVER_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: shlink-secret
                    key: SHLINK_API_KEY
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
    service:
      app:
        controller: shlink
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.kinzoku.dev
          nginx.ingress.kubernetes.io/auth-url: |-
            http://authentik-proxy.security.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
            https://shlink.kinzoku.dev/outpost.goauthentik.io/start?rd=$escaped_request_uri
        hosts:
          - host: &host shlink.kinzoku.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
