---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shlink
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: shlink-secret
    template:
      engineVersion: v2
      data:
        SHLINK_API_KEY: "{{ .SHLINK_API_KEY }}"
  dataFrom:
    - extract:
        key: shlink
