---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app shlink
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      shlink:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          geoip:
            image:
              repository: ghcr.io/shlinkio/shlink
              tag: 4.4.6-roadrunner@sha256:f757d0f668acd9b670ff8b7d07be82e0e1f5446911d5938c4d0de615fc87a03d
              pullPolicy: IfNotPresent
            command:
              - sh
              - -c
              - |
                set -eux
                cp -a ./vendor/shlinkio/shlink-ip-geolocation/src/GeoLite2/* /geoip
                sed -i 's|https://download.maxmind.com|http://geoip-download.geoip|' \
                  /geoip/GeoLite2Options.php
        containers:
          app:
            image:
              repository: ghcr.io/shlinkio/shlink
              tag: 4.4.6@sha256:1a697baca56ab8821783e0ce53eb4fb22e51bb66749ec50581adc0cb6d031d7a
            env:
              TIMEZONE: "America/New_York"
              DEFAULT_DOMAIN: "l.kinzoku.dev"
              DISABLE_TRACKING_FROM: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
              IS_HTTPS_ENABLED: "true"
              PORT: &port 80
              SHELL_VERBOSITY: 3
              TASK_WORKER_NUM: 4
              WEB_WORKER_NUM: 1
              GEOLITE_LICENSE_KEY: stub
              SKIP_INITIAL_GEOLITE_DOWNLOAD: "true"
              DB_DRIVER: postgres
              DB_HOST:
                valueFrom:
                  secretKeyRef:
                    name: &pgsec "shlink-pg-app"
                    key: host
              DB_NAME:
                valueFrom:
                  secretKeyRef:
                    name: *pgsec
                    key: dbname
              DB_USER:
                valueFrom:
                  secretKeyRef:
                    name: *pgsec
                    key: username
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: *pgsec
                    key: password
              INITIAL_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: &shlsec shlink-secret
                    key: SHLINK_API_KEY
            securityContext:
              runAsNonRoot: true
              runAsUser: 1001
              runAsGroup: 1001
              fsGroup: 1001
              fsGroupChangePolicy: OnRootMismatch
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /rest/health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
          web:
            image:
              repository: ghcr.io/shlinkio/shlink-web-client
              tag: 4.4.0@sha256:99988516ee0caf2059a485edaacab9759db0a3140c5a5c2634e0a97ac4d194bf
            env:
              TIMEZONE: "America/New_York"
              SHLINK_SERVER_URL: "https://l.kinzoku.dev"
              SHLINK_SERVER_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: *shlsec
                    key: SHLINK_API_KEY
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
          web:
            port: 8080
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.kinzoku.dev
        hosts:
          - host: l.kinzoku.dev
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
      web:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.kinzoku.dev
        hosts:
          - host: shlink.kinzoku.dev
            paths:
              - path: /
                service:
                  identifier: app
                  port: web
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      tmp-data:
        type: emptyDir
        globalMounts:
          - path: /etc/shlink/data
      geolite2:
        type: emptyDir
        advancedMounts:
          shlink:
            geoip:
              - path: /geoip
            app:
              - path: /etc/shlink/vendor/shlinkio/shlink-ip-geolocation/src/GeoLite2
                readOnly: true
