---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app shlink
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      shlink:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/shlinkio/shlink
              tag: 4.4.6@sha256:1a697baca56ab8821783e0ce53eb4fb22e51bb66749ec50581adc0cb6d031d7a
            env:
              TIMEZONE: "America/New_York"
              DEFAULT_DOMAIN: "l.kinzoku.dev"
              IS_HTTPS_ENABLED: "true"
              PORT: &port 8080
              DB_DRIVER: postgres
              DB_HOST:
                valueFrom:
                  secretKeyRef:
                    name: &pgsec "shlink-pg-app"
                    key: host
              DB_NAME:
                valueFrom:
                  secretKeyRef:
                    name: *pgsec
                    key: dbname
              DB_USER:
                valueFrom:
                  secretKeyRef:
                    name: *pgsec
                    key: username
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: *pgsec
                    key: password
              INITIAL_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: &shlsec shlink-secret
                    key: SHLINK_API_KEY
              GEOLITE_LICENSE_KEY:
                valueFrom:
                  secretKeyRef:
                    name: *shlsec
                    key: MAXMIND_LICENSE_KEY
            securityContext:
              runAsNonRoot: true
              runAsUser: 1001
              runAsGroup: 1001
              fsGroup: 1001
              fsGroupChangePolicy: OnRootMismatch
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /rest/health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.kinzoku.dev
        hosts:
          - host: l.kinzoku.dev
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /etc/shlink/data
      log:
        type: emptyDir
        globalMounts:
          - path: /etc/shlink/data/log
