---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app navidrome
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      navidrome:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/navidrome/navidrome
              tag: 0.57.0@sha256:d753f3f0ba65d838d288e58c2cb1254a519f439b88fa0fa8378178f5e8b17587
            env:
              ND_SCANSCHEDULE: 30m
              ND_DATAFOLDER: /data
              ND_LOGLEVEL: info
              ND_ENABLEDOWNLOADS: "true"
              ND_ENABLEEXTERNALSERVICES: "true"
              ND_ENABLESHARING: "true"
              ND_ENABLESTARRATING: "true"
              ND_MUSICFOLDER: /music
              ND_PORT: &port 4533
              ND_BASEURL: https://nd.kinzoku.dev
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 5m
                memory: 799Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.kinzoku.dev
        hosts:
          - host: nd.kinzoku.dev
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /data
      media:
        type: nfs
        server: singularity.internal
        path: /mnt/data/media/music
        globalMounts:
          - path: /music
