---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gatus-secret
    template:
      engineVersion: v2
      data:
        CUSTOM_PUSHOVER_TOKEN: '{{ .GATUS_PUSHOVER_TOKEN }}'
        CUSTOM_PUSHOVER_USER_KEY: '{{ .PUSHOVER_USER_KEY }}'
  dataFrom:
    - extract:
        key: gatus
    - extract:
        key: pushover
