---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: external-secrets
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.17.0@sha256:98afa324984e42c69808b76efcce8869e5b0da2d27326aaf81d35316ae4e0e47
  url: oci://ghcr.io/external-secrets/charts/external-secrets
  verify:
    provider: cosign
